### ISSUE TITLE
FFmpeg subprocess sometimes hangs

### ISSUE THREAD

**Issue by barthanssens** [mfalesni/Beheaded#2]
On Debian 7 with ffmpeg/libav and Python 2.7.8

When Record is stopped after having recorded video for a few minutes, the subprocess running ffmpeg sometimes hangs (the size of the videofile does not grow anymore, ffmpeg is not using CPU anymore, so it just waits)

I've written a small patch for this (see pull request nr 1)

**Comment by mfalesni** [comment]
Closed by #1
